### ISSUE TITLE
AttributeError: module 'formulaic' has no attribute 'ModelSpec'

### ISSUE THREAD

**Issue by timscorbett** [CamDavidsonPilon/lifelines#1561]
Is this a known issue? DOes this have a resolution already?

Traceback (most recent call last):
  File "C:\Users\tims\conda_projects\battery\pipes\lifelines_example.py", line 22, in <module>
    weibull_aft.fit(df, duration_col='T', event_col='E')
  File "C:\Users\tims\.conda\envs\battery\lib\site-packages\lifelines\utils\__init__.py", line 56, in f
    return function(model, *args, **kwargs)
  File "C:\Users\tims\.conda\envs\battery\lib\site-packages\lifelines\fitters\__init__.py", line 2872, in fit
    super(ParametericAFTRegressionFitter, self)._fit(
  File "C:\Users\tims\.conda\envs\battery\lib\site-packages\lifelines\fitters\__init__.py", line 1817, in _fit
    self.regressors = utils.CovariateParameterMappings(
  File "C:\Users\tims\.conda\envs\battery\lib\site-packages\lifelines\utils\__init__.py", line 1880, in __init__
    self.mappings[param] = self._string_seed_transform(seed_transform, df)
  File "C:\Users\tims\.conda\envs\battery\lib\site-packages\lifelines\utils\__init__.py", line 1957, in _string_seed_transform
    design_info = formulaic.ModelSpec.from_spec(formulaic.Formula(formula).get_model_matrix(df))
AttributeError: module 'formulaic' has no attribute 'ModelSpec'

**Comment by CamDavidsonPilon** [comment]
Hi @timscorbett, 

Which version of formulaic and lifelines do you have (`pip list` to see)?

**Comment by timscorbett** [comment]
formulaic==0.2.4
lifelines==0.27.8



Thanks,


Tims
