### ISSUE TITLE
ImportError: No module named lifelines.datasets

### ISSUE THREAD

**Issue by ZzDizzyBearzZ** [CamDavidsonPilon/lifelines#416]
Hi Everyone, I am currently having this Error. 
Do anyone have any idea of how to solve this error?

File "27NovTest.py", line 1, in <module>
from lifelines.datasets import load_dataset 
ImportError: No module named lifelines.datasets

Thanks in Advance

**Comment by CamDavidsonPilon** [comment]
How did you install lifelines, @ZzDizzyBearzZ?

**Comment by jamesTheKid** [comment]
Have the same issue here.

**Comment by CamDavidsonPilon** [comment]
How did you install lifelines, @jamesTheKid?

**Comment by ZzDizzyBearzZ** [comment]
Hi! I installed Lifelines using pip install lifelines and tried pip install --upgrade git+https://github.com/CamDavidsonPilon/lifelines.git

I believe I might have tried using pip3 install

**Comment by ZzDizzyBearzZ** [comment]
The error became what it is shown below

Admins-MacBook-Pro-2:desktop admin$ python3 27NovTest.py
Traceback (most recent call last):
  File "27NovTest.py", line 9, in <module>
    df = load_smrtData() # returns a Pandas DataFrame
  File "27NovTest.py", line 7, in load_xxxxData
    return load_dataset('C:/Users/admin/Desktop/xxxxUpdatedDatasetData.csv', **kwargs)
  File "/usr/local/lib/python3.6/site-packages/lifelines/datasets/__init__.py", line 18, in load_dataset
    engine='python', **kwargs)
  File "/usr/local/lib/python3.6/site-packages/pandas/io/parsers.py", line 709, in parser_f
    return _read(filepath_or_buffer, kwds)
  File "/usr/local/lib/python3.6/site-packages/pandas/io/parsers.py", line 449, in _read
    parser = TextFileReader(filepath_or_buffer, **kwds)
  File "/usr/local/lib/python3.6/site-packages/pandas/io/parsers.py", line 818, in __init__
    self._make_engine(self.engine)
  File "/usr/local/lib/python3.6/site-packages/pandas/io/parsers.py", line 1059, in _make_engine
    self._engine = klass(self.f, **self.options)
  File "/usr/local/lib/python3.6/site-packages/pandas/io/parsers.py", line 2074, in __init__
    memory_map=self.memory_map)
  File "/usr/local/lib/python3.6/site-packages/pandas/io/common.py", line 393, in _get_handle
    f = open(path_or_buf, mode, errors='replace')
FileNotFoundError: [Errno 2] No such file or directory: '/usr/local/lib/python3.6/site-packages/lifelines/datasets/C:/Users/admin/Desktop/xxxxUpdatedDatasetData.csv'

**Comment by ZzDizzyBearzZ** [comment]
I solved the problem by checking the version and reinstall the python and lifeline.

To check the python version: python --version
brew doctor
brew install python3
python3 --version
pip3 install lifelines

**Comment by jamesTheKid** [comment]
@CamDavidsonPilon I solved my issue by running ipython3 instead of ipython.

**Comment by davidrindt** [comment]
Same here after installing with anaconda

**Comment by davidrindt** [comment]
I have the same issue after installing lifelines seemingly correctly using anaconda package manager. But then running the code in Spyder gives the error  ```
line 3, in <module>
    import lifelines
  File "C:\Users\David\Documents\git\2sampletest\lifelines.py", line 2, in <module>
    from lifelines.datasets import load_waltons
ModuleNotFoundError: No module named 'lifelines.datasets'; 'lifelines' is not a package

```
