### ISSUE TITLE
import WeibullAFTFitter shows: No module named 'future.utils'

### ISSUE THREAD

**Issue by binshuangli** [CamDavidsonPilon/lifelines#683]
I'm trying to experiment the WeibullAFTFitter. I upgraded lifelines to 0.20.4 using pip. However, when I tried to import WeibullAFTFitter, it reported ImportError: No module named 'future.utils'
I checked my environment, there is future package (0.17.1) installed.

**Comment by CamDavidsonPilon** [comment]
hm, thanks for the report. Let me investigate a bit. Can you post the entire stacktrace? 
What version of pandas do you have installed? `pip freeze` will show you.

**Comment by CamDavidsonPilon** [comment]
Can you confirm that 0.20.3 _doesn't_ have this problem, also?

**Comment by binshuangli** [comment]
Hi, thanks for getting back to me. My pandas==0.24.2
the full stack of error is as follows. I tried 0.20.3 and it has the same problem.

>>> from lifelines import WeibullAFTFitter
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "C:\Anaconda3\envs\experiment_env\lib\site-packages\lifelines\__init__.py", line 4, in <module>
    from lifelines.fitters.weibull_fitter import WeibullFitter
  File "C:\Anaconda3\envs\experiment_env\lib\site-packages\lifelines\fitters\__init__.py", line 16, in <module>
    import autograd.numpy as anp
  File "C:\Anaconda3\envs\experiment_env\lib\site-packages\autograd\__init__.py", line 2, in <module>
    from .differential_operators import (
  File "C:\Anaconda3\envs\experiment_env\lib\site-packages\autograd\differential_operators.py", line 12, in <module>
    import autograd.numpy as np
  File "C:\Anaconda3\envs\experiment_env\lib\site-packages\autograd\numpy\__init__.py", line 2, in <module>
    from .numpy_wrapper import *
  File "C:\Anaconda3\envs\experiment_env\lib\site-packages\autograd\numpy\numpy_wrapper.py", line 6, in <module>
    import autograd.builtins as builtins
  File "C:\Anaconda3\envs\experiment_env\lib\site-packages\autograd\builtins.py", line 2, in <module>
    from future.utils import with_metaclass
ImportError: No module named 'future.utils'

**Comment by CamDavidsonPilon** [comment]
hm, I can't see why it would fail. Can you confirm 
```
conda install -c anaconda future 

```
runs without failing?

**Comment by binshuangli** [comment]
Hi Cam, I figured it out. It's the problem with the pip installed version of future. I uninstalled it and reinstalled with conda. Now it is working. Thank you!

**Comment by WellJoea** [comment]
I have the same problem.
