### ISSUE TITLE
Source installation doesn't work due to `reqs`

### ISSUE THREAD

**Issue by AbdealiJK** [CamDavidsonPilon/lifelines#900]
When doing a source installation from pip:
`pip install --no-binary :all: lifelines`
it fails with:
```
  Downloading https://files.pythonhosted.org/packages/cd/7e/5787389141567ef38b94f1d06922d010644e32b55e471a13f80b3e1d2b2c/lifelines-0.23.3.tar.gz (321kB)
  Saved ./pypi/downloads/lifelines-0.23.3.tar.gz
    Complete output from command python setup.py egg_info:
    Traceback (most recent call last):
      File "<string>", line 1, in <module>
      File "/private/var/folders/g8/blwgm8mx7dng2pflkt7rwy0m0000gn/T/pip-download-kntrfzgd/lifelines/setup.py", line 8, in <module>
        with open("reqs/base-requirements.txt") as f:
    FileNotFoundError: [Errno 2] No such file or directory: 'reqs/base-requirements.txt'
```
The `reqs` folder isnt present in lifelines

**Comment by CamDavidsonPilon** [comment]
oooo this might be the solution to #852!

**Comment by CamDavidsonPilon** [comment]
v0.23.4 was pushed to PyPI
